import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium, webkit } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const url = process.env.TEST_URL || 'http://127.0.0.1:4173';
const output = process.env.QA_OUTPUT || 'test-results';
await mkdir(output, { recursive: true });
const engines = process.env.QA_WEBKIT === '1' ? [chromium, webkit] : [chromium];
const report = [];
for (const engine of engines) {
  const browser = await engine.launch({ headless: true, ...(engine === chromium && process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
  for (const width of [360, 390, 430, 768, 1440]) {
    const context = await browser.newContext({ viewport: { width, height: width > 1000 ? 1000 : 844 }, isMobile: width < 600, hasTouch: width < 600, reducedMotion: 'no-preference' });
    const page = await context.newPage();
    const errors = [];
    const mediaRequests = [];
    page.on('pageerror', (error) => errors.push(error.message));
    page.on('request', (request) => { if (request.url().includes('recorrido.mp4')) mediaRequests.push(request.url()); });
    page.on('response', (response) => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
    await page.goto(url, { waitUntil: 'networkidle' });
    assert.equal(mediaRequests.length, 0, `${engine.name()} ${width}: no initial video request`);
    assert.equal(await page.locator('#tour-video').getAttribute('src'), null);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${width}: overflow`);
    assert.equal(await page.locator('.whatsapp').count(), 3);
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.floating-whatsapp')).visibility === 'hidden');
    await page.screenshot({ path: `${output}/${engine.name()}-${width}-hero.png` });
    if (width < 1000) {
      await page.locator('.menu-toggle').click();
      assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'true');
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
    }
    await page.locator('#video-card').scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector('#tour-video').currentTime > .2);
    assert(mediaRequests.length > 0);
    assert(await page.locator('#tour-video').evaluate((e) => e.muted));
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.floating-whatsapp')).visibility === 'hidden');
    await page.locator('#video-toggle').click();
    await page.waitForTimeout(350);
    assert(await page.locator('#tour-video').evaluate((e) => e.paused));
    const pausedAt = await page.locator('#tour-video').evaluate((e) => e.currentTime);
    await page.locator('#habitaciones').scrollIntoViewIfNeeded();
    await page.locator('#video-card').scrollIntoViewIfNeeded();
    await page.waitForTimeout(300);
    assert(await page.locator('#tour-video').evaluate((e) => e.paused), 'User pause survives re-entry');
    await page.locator('#video-toggle').click();
    await page.waitForFunction(() => !document.querySelector('#tour-video').paused);
    assert(await page.locator('#tour-video').evaluate((e, t) => e.currentTime >= t, pausedAt), 'Playback position retained');
    await page.locator('#sound-toggle').click();
    await page.waitForFunction(() => document.querySelector('#sound-toggle').getAttribute('aria-pressed') === 'true');
    assert.equal(await page.locator('#sound-toggle').getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('#tour-video').evaluate((e) => e.muted), false);
    await page.locator('#sound-toggle').click();
    await page.locator('#ubicacion').scrollIntoViewIfNeeded();
    await page.waitForTimeout(300);
    assert(await page.locator('#tour-video').evaluate((e) => e.paused), 'Pauses offscreen');
    await page.locator('#see-all').click();
    assert(await page.locator('#lightbox').evaluate((e) => e.open));
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#lightbox-count').textContent(), '02 / 12');
    await page.keyboard.press('ArrowLeft');
    assert.equal(await page.locator('#lightbox-count').textContent(), '01 / 12');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#lightbox').evaluate((e) => e.open), false);
    assert(await page.locator('#see-all').evaluate((e) => document.activeElement === e));
    await page.locator('#contacto').scrollIntoViewIfNeeded();
    await page.waitForTimeout(250);
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.floating-whatsapp')).visibility === 'hidden');
    // Warm lazy images before the complete visual capture.
    for (const selector of ['#el-lugar', '#recorrido', '#habitaciones', '.bathrooms', '#galeria', '.amenities', '#ubicacion', '#contacto']) { await page.locator(selector).scrollIntoViewIfNeeded(); await page.waitForTimeout(100); }
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.waitForTimeout(200);
    await page.screenshot({ path: `${output}/${engine.name()}-${width}-full.png`, fullPage: true });
    assert.deepEqual(errors, []);
    report.push({ engine: engine.name(), width, status: 'passed', initialVideoRequests: 0, checks: ['no overflow', 'menu', 'lazy video', 'autoplay muted', 'tap pause/resume', 'manual pause retained', 'sound control', 'offscreen pause', 'gallery keyboard/focus', 'floating CTA visibility', 'no runtime/network errors'] });
    await context.close();
  }
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce', isMobile: true });
  const page = await context.newPage();
  const requests = [];
  page.on('request', (r) => { if (r.url().includes('recorrido.mp4')) requests.push(r.url()); });
  await page.goto(url, { waitUntil: 'networkidle' });
  await page.locator('#video-card').scrollIntoViewIfNeeded();
  await page.waitForTimeout(400);
  assert.equal(requests.length, 0, 'Reduced motion: no automatic video request');
  await page.locator('#video-toggle').click();
  await page.waitForFunction(() => document.querySelector('#tour-video').currentTime > .2);
  assert(requests.length > 0, 'Reduced motion: explicit playback works');
  report.push({ engine: engine.name(), reducedMotion: 'passed' });
  await context.close();
  const fallback = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  const fallbackPage = await fallback.newPage();
  await fallbackPage.goto(url);
  assert(await fallbackPage.locator('.video-fallback').isVisible());
  assert(await fallbackPage.locator('.gallery-item').last().isVisible());
  assert(await fallbackPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  report.push({ engine: engine.name(), noJavaScript: 'passed' });
  await fallback.close();
  await browser.close();
}
await writeFile(`${output}/report.json`, JSON.stringify(report, null, 2));
console.log(JSON.stringify(report, null, 2));
