import { readFile, stat } from 'node:fs/promises';
import assert from 'node:assert/strict';
const html = await readFile('dist/index.html', 'utf8');
assert(!html.includes('{{'), 'Unresolved template');
assert(!/\ssrc=/.test(html.match(/<video id="tour-video"[^>]*>/)[0]), 'Enhanced video must have no initial src');
assert(html.includes('preload="none"') && html.includes('playsinline'), 'Video mobile attributes');
for (const match of html.matchAll(/(?:src|href|poster)="(\.\/[^"?#]+)"/g)) await stat(`dist/${match[1].slice(2)}`);
assert((html.match(/fetchpriority="high"/g) || []).length === 1, 'Only hero receives high priority');
assert((html.match(/<h1>/g) || []).length === 1, 'Exactly one primary heading');
assert(html.includes('<html lang="es-AR">') && html.includes('<meta charset="utf-8">'), 'Spanish locale and UTF-8');
assert(html.includes('<meta name="robots" content="index, follow">'), 'Page is indexable');
assert.equal((html.match(/rel="canonical"/g) || []).length, 1, 'Exactly one canonical URL');
const requiredMeta = ['og:type','og:locale','og:site_name','og:title','og:description','og:image','og:image:secure_url','og:image:width','og:image:height','og:image:alt','og:url','twitter:card','twitter:title','twitter:description','twitter:image','twitter:image:alt'];
for (const property of requiredMeta) assert(html.includes(`property="${property}"`) || html.includes(`name="${property}"`), `Metadata ${property}`);
assert(html.includes('content="index, follow"') && html.includes('content="summary_large_image"'), 'Indexing and large social card');
const canonical = html.match(/<link rel="canonical" href="([^"]+)"/)[1];
assert.equal(canonical, 'https://alquilerapp.vercel.app/', 'Verified production canonical URL');
const socialUrl = html.match(/<meta property="og:image" content="([^"]+)"/)[1];
assert.equal(socialUrl, 'https://alquilerapp.vercel.app/social-preview.jpg', 'Absolute HTTPS social image URL');
assert.equal(html.match(/<meta property="og:image:width" content="([^"]+)"/)[1], '1200');
assert.equal(html.match(/<meta property="og:image:height" content="([^"]+)"/)[1], '630');
assert((await stat('dist/social-preview.jpg')).size < 400_000, 'Social image budget < 400 KB');
const jsonLd = JSON.parse(html.match(/<script type="application\/ld\+json">([^<]+)<\/script>/)[1]);
assert.equal(jsonLd['@type'], 'WebPage');
assert.equal(jsonLd.inLanguage, 'es-AR');
assert.equal(jsonLd.url, canonical);
assert.equal(jsonLd.mainEntity['@type'], 'Accommodation');
assert.equal(jsonLd.mainEntity.numberOfRooms, 3);
assert.equal(jsonLd.mainEntity.numberOfBathroomsTotal, 2);
assert.equal(jsonLd.mainEntity.petsAllowed, false);
assert(!JSON.stringify(jsonLd).includes('streetAddress'));
assert((await stat('dist/media/recorrido.mp4')).size < 7 * 1024 * 1024, 'Video budget < 7 MiB');
assert((await stat('dist/media/hero-480.webp')).size < 160 * 1024, 'Mobile hero budget < 160 KiB');
console.log('Asset links, video loading, SEO/social metadata, structured facts and media budgets passed.');
